### ISSUE TITLE
Panic on non-UTF-8 filenames

### ISSUE THREAD

**Issue by bluss** [phildawes/racer#268]
This occurs if there's a non-UTF-8 filename in the local directory and I use `racer`.

```
$ RUST_BACKTRACE=1 racer complete foo::
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/option.rs:362
stack backtrace:
   1:     0x7fb2c9bcceb3 - sys::backtrace::write::h78d8566ea57298318cs
   2:     0x7fb2c9bd05b1 - panicking::on_panic::h1828971352b87f32XXw
   3:     0x7fb2c9bc2cba - rt::unwind::begin_unwind_inner::h70b8a47e7ca8c04aHDw
   4:     0x7fb2c9bc3217 - rt::unwind::begin_unwind_fmt::hdf51072a712c38a2NCw
   5:     0x7fb2c9bcff06 - rust_begin_unwind
   6:     0x7fb2c9c00214 - panicking::panic_fmt::hdda338ab4cb55cc9i5B
   7:     0x7fb2c9bfd684 - panicking::panic::hc292adbdce9c349dP3B
   8:     0x7fb2c9a412ab - racer::nameres::do_file_search::h3ecc22ed3048e8609Jd
                        at /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/macros.rs:19   
                        at src/racer/nameres.rs:314
   9:     0x7fb2c9a71e4e - complete::h834cc3fdbb4e04dalLi
                        at src/main.rs:90
  10:     0x7fb2c9a75894 - main::h8107ca8fa2d8ecf5m0i
                        at src/main.rs:186
  11:     0x7fb2c9bd5518 - rust_try_inner
  12:     0x7fb2c9bd5505 - rust_try
  13:     0x7fb2c9bd1e03 - rt::lang_start::hc0160dc27b69e1c51Sw
  14:     0x7fb2c9437b44 - __libc_start_main
  15:     0x7fb2c9a03ba8 - <unknown>
  16:                0x0 - <unknown>
```

rustc: rustc 1.2.0-nightly (2228ce10c 2015-06-09)

racer: 68829343ba4afdbb20be624cd1ab9f25cdbb3a42

**Comment by phildawes** [comment]
Thanks @bluss, Marking as a bug

**Comment by llogiq** [comment]
The solution would be to make Match take an OsString instead of String, right?
