### ISSUE TITLE
panic when matching byte string literals

### ISSUE THREAD

**Issue by crumblingstatue** [phildawes/racer#494]
``` Rust
fn main() {
    match b"foo" {
        b"foo" => u,
        _ => unimplemented!(),
    }
}
```

```
$ racer complete 3 19 src/main.rs 
PREFIX 18,19,u
error: internal compiler error: Error constructed but not emitted
thread 'searcher' panicked at 'explicit panic', /home/snake/.multirust/cargo/registry/src/github.com-88ac128001ac3a9a/syntex_syntax-0.26.0/src/errors/mod.rs:261
stack backtrace:
   1:     0x562712eb4920 - sys::backtrace::tracing::imp::write::ha2266db58ba01299Inu
   2:     0x562712eb6fd5 - panicking::default_handler::_<closure>::closure.42772
   3:     0x562712eb6ba4 - panicking::default_handler::ha9185fa175181c37aFy
   4:     0x562712ea6436 - sys_common::unwind::begin_unwind_inner::hd2581d64e3d2c165fgt
   5:     0x562712d18274 - sys_common::unwind::begin_unwind::h14302563943743593042
                        at ../src/libstd/sys/common/unwind/mod.rs:227
   6:     0x562712d1a03e - errors::DiagnosticBuilder<'a>.Drop::drop::he24c5e2ec4c87467j1c
                        at /home/snake/projects/github/phildawes/racer/<std macros>:3
   7:     0x562712c60e37 - ast::string_to_stmt::h5a26b51c975a3019TAb
                        at src/racer/ast.rs:45
                        at src/racer/ast.rs:35
                        at src/racer/ast.rs:40
   8:     0x562712c82e7d - ast::parse_pat_idents::h6021142aa2236acaLPc
                        at src/racer/ast.rs:871
   9:     0x562712ca56e1 - nameres::search_local_scopes::hbeab58c8e52c56beELe
                        at src/racer/nameres.rs:266
                        at src/racer/nameres.rs:748
  10:     0x562712c98097 - nameres::resolve_name::h8f8c08523efa6c8aw1e
                        at src/racer/nameres.rs:875
  11:     0x562712c543a9 - nameres::resolve_path::hbd85368339a7d33cnbf
                        at src/racer/nameres.rs:954
  12:     0x562712c52299 - core::complete_from_file::hd5becb7cbe95dc77b3a
                        at src/racer/core.rs:583
  13:     0x562712c21acd - sys_common::unwind::try::try_fn::h10035944982268650571
                        at src/bin/main.rs:139
                        at src/bin/main.rs:105
                        at ../src/libstd/thread/mod.rs:277
                        at ../src/libstd/sys/common/unwind/mod.rs:153
  14:     0x562712eb3ef8 - __rust_try
  15:     0x562712eb14cb - sys_common::unwind::try::inner_try::hdf22e8290aaddbc5Nct
  16:     0x562712c22a25 - boxed::F.FnBox<A>::call_box::h1571034592768641712
                        at ../src/libstd/sys/common/unwind/mod.rs:123
                        at ../src/libstd/thread/mod.rs:277
                        at ../src/liballoc/boxed.rs:541
  17:     0x562712eb5b03 - sys::thread::Thread::new::thread_start::h78065079e52526f86Bx
  18:     0x7f66e61304a3 - start_thread
  19:     0x7f66e5c5813c - clone
  20:                0x0 - <unknown>
ERROR:racer: Search thread paniced: Any
END

```

**Comment by phildawes** [comment]
Thanks for the issue @crumblingstatue. This is a bug with the way racer attempts to fix up match statements for parsing. On my box with a release build the panic stacktrace takes a while to be printed (causing emacs to pause!) - is that universal?

N.B. with 1.2.2 this fails quickly so I guess something changed with the parser between syntex 0.24 and 0.26
```
$ target/release/racer complete 3 19 /tmp/a1.rs
PREFIX 18,19,u
bogofile:1:17: 1:19 error: unexpected token: `=>`
bogofile:1 match b"   " {  => () };
                           ^~
END
```

**Comment by crumblingstatue** [comment]
> On my box with a release build the panic stacktrace takes a while to be printed (causing emacs to pause!) - is that universal?

Yes, it takes a while on my system too.

**Comment by crumblingstatue** [comment]
This doesn't seem to cause an ICE anymore, so closing.
