### ISSUE TITLE
Racer 1.2.10 panics in searcher thread when trying to unwrap on a None value

### ISSUE THREAD

**Issue by DamnWidget** [phildawes/racer#569]
I rant into this issue in several files and locations over several projects, I am afraid that I can't be more specific or useful about why this occurs but it seems to be pretty random issue. Anyway I was just able to come up with a simple enough piece of code that replicates the issue.

```rust
use std::io;

fn main() {
    io::
}
```

When you run racer on it:
```
RUST_BACKTRACE=1 racer -i tab-text complete-with-snippet 4 8 /home/damnwidget/development/racerd/src/http/pollas.rs                                                                                                                                                            
PREFIX  8       8
thread 'searcher' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:325
stack backtrace:
   1:     0x564ddf400790 - std::sys::backtrace::tracing::imp::write::h9fb600083204ae7f
   2:     0x564ddf40409b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hca543c34f11229ac
   3:     0x564ddf403d23 - std::panicking::default_hook::hc2c969e7453d080c
   4:     0x564ddf3f42f8 - std::panicking::rust_panic_with_hook::hfe203e3083c2b544
   5:     0x564ddf4042e1 - std::panicking::begin_panic::h4889569716505182
   6:     0x564ddf3f53ca - std::panicking::begin_panic_fmt::h484cd47786497f03
   7:     0x564ddf40427e - rust_begin_unwind
   8:     0x564ddf439f8f - core::panicking::panic_fmt::h257ceb0aa351d801
   9:     0x564ddf43a268 - core::panicking::panic::h4bb1497076d04ab9
  10:     0x564ddf24818f - racer::cargo::get_package_name::hf3c99cca0c172307
                        at ../src/libcore/macros.rs:21
                        at /home/damnwidget/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-1.2.10/src/racer/cargo.rs:168
  11:     0x564ddf246814 - racer::cargo::find_src_via_lockfile::hb537490bd09cd201
                        at /home/damnwidget/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-1.2.10/src/racer/cargo.rs:80
  12:     0x564ddf22a8c2 - racer::cargo::get_crate_file::h5d6e19bf8ab1ff99
                        at /home/damnwidget/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-1.2.10/src/racer/cargo.rs:483
  13:     0x564ddf229e56 - racer::nameres::get_crate_file::h6f160050700fcab3
                        at /home/damnwidget/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-1.2.10/src/racer/nameres.rs:508
  14:     0x564ddf226309 - racer::nameres::resolve_name::h39762a57b0acccf9
                        at /home/damnwidget/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-1.2.10/src/racer/nameres.rs:876
  15:     0x564ddf1e1642 - racer::nameres::resolve_path::h561805765ebda3ef
                        at /home/damnwidget/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-1.2.10/src/racer/nameres.rs:976
  16:     0x564ddf1e199d - racer::nameres::resolve_path::h561805765ebda3ef
                        at /home/damnwidget/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-1.2.10/src/racer/nameres.rs:1003
  17:     0x564ddf23d675 - racer::matchers::match_use::hd371b37336f47c09
                        at /home/damnwidget/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-1.2.10/src/racer/matchers.rs:563
  18:     0x564ddf22d17d - racer::matchers::match_types::h54262be06fa19aac
                        at /home/damnwidget/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-1.2.10/src/racer/matchers.rs:27
  19:     0x564ddf22b41a - racer::nameres::run_matchers_on_blob::h576a83458a0b28d8
                        at /home/damnwidget/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-1.2.10/src/racer/nameres.rs:698
  20:     0x564ddf228f11 - racer::nameres::search_scope::hfc274f3a72915d17
                        at /home/damnwidget/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-1.2.10/src/racer/nameres.rs:665
  21:     0x564ddf22f766 - racer::nameres::search_local_scopes::h6e51c11008256407
                        at /home/damnwidget/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-1.2.10/src/racer/nameres.rs:753
  22:     0x564ddf2265a9 - racer::nameres::resolve_name::h39762a57b0acccf9
                        at /home/damnwidget/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-1.2.10/src/racer/nameres.rs:897
  23:     0x564ddf1e1642 - racer::nameres::resolve_path::h561805765ebda3ef
                        at /home/damnwidget/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-1.2.10/src/racer/nameres.rs:976
  24:     0x564ddf1e199d - racer::nameres::resolve_path::h561805765ebda3ef
                        at /home/damnwidget/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-1.2.10/src/racer/nameres.rs:1003
  25:     0x564ddf1dff53 - racer::core::complete_from_file::hd59f42a7f7e40a47
                        at /home/damnwidget/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-1.2.10/src/racer/core.rs:661
  26:     0x564ddf1452f0 - std::panicking::try::call::h475b6147c132ae0f
                        at /home/damnwidget/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-1.2.10/src/bin/main.rs:160
                        at /home/damnwidget/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-1.2.10/src/bin/main.rs:109
                        at ../src/libstd/panic.rs:284
                        at ../src/libstd/panicking.rs:272
  27:     0x564ddf40df5b - __rust_try
  28:     0x564ddf40defe - __rust_maybe_catch_panic
  29:     0x564ddf145c13 - _<F as std..boxed..FnBox<A>>::call_box::hecc719901df21385
                        at ../src/libstd/thread/local.rs:211
                        at ../src/libstd/panicking.rs:235
                        at ../src/libstd/panic.rs:387
                        at ../src/liballoc/boxed.rs:543
  30:     0x564ddf4027b4 - std::sys::thread::Thread::new::thread_start::h6f266e069bf4ec2b
  31:     0x7fc8a4bc0483 - start_thread
  32:     0x7fc8a46e96dc - clone
  33:                0x0 - <unknown>
ERROR:racer: Search thread paniced: Any
END
```

It works fine with previous versions (1.2.9 at least)

**Comment by DamnWidget** [comment]
Anyway, it seems to be fixed in the master branch.

**Comment by jwilm** [comment]
@DamnWidget can this be closed then?

**Comment by DamnWidget** [comment]
Yup, I think so
