### ISSUE TITLE
Racer is slicing out of boundary 0..(u64-1)

### ISSUE THREAD

**Issue by sekjun9878** [phildawes/racer#582]
Hello,

I have a very weird issue that I'm wondering if you'll be able to reproduce? This is on the master branch.

```
sekjun9878@workstation1:~$ cargo install -j 8 --git https://github.com/phildawes/racer.git --force
    Updating git repository `https://github.com/phildawes/racer.git`
   Compiling rustc-serialize v0.3.19
   Compiling strsim v0.4.0
   Compiling bitflags v0.5.0
   Compiling ansi_term v0.7.2
   Compiling libc v0.2.9
   Compiling unicode-xid v0.0.3
   Compiling winapi-build v0.1.1
   Compiling regex-syntax v0.3.1
   Compiling utf8-ranges v0.1.3
   Compiling mempool v0.3.0
   Compiling vec_map v0.6.0
   Compiling kernel32-sys v0.2.1
   Compiling log v0.3.6
   Compiling typed-arena v1.1.0
   Compiling unicode-width v0.1.3
   Compiling winapi v0.2.6
   Compiling bitflags v0.4.0
   Compiling memchr v0.1.11
   Compiling clap v2.2.5
   Compiling aho-corasick v0.5.1
   Compiling term v0.2.14
   Compiling toml v0.1.28
   Compiling syntex_syntax v0.32.0
   Compiling regex v0.1.62
   Compiling env_logger v0.3.3
   Compiling racer v1.2.10 (https://github.com/phildawes/racer.git#887e3454)
   Replacing /home/sekjun9878/.cargo/bin/racer
sekjun9878@workstation1:~$ date
Friday 29 July  00:57:15 ACST 2016
sekjun9878@workstation1:~$ 
```

```
sekjun9878@workstation1:~/Projects/news-test$ RUST_BACKTRACE=1 racer complete 19 9 src/main2.rs
PREFIX 9,9,
thread 'searcher' panicked at 'index 0 and/or 18446744073709551615 in `extern crate regex;

#[macro_use]
extern crate log;
extern crate env_logger;

extern crate serde_json;
extern crate postgres;
extern crate select;
extern crate chrono;

use std::fs::File;
use std::io::Write;
use std::io::Read;
use std::collections::HashMap`[...] do not lie on character boundary', ../src/libcore/str/mod.rs:1711
stack backtrace:
   1:     0x7f00663864ef - std::sys::backtrace::tracing::imp::write::h6528da8103c51ab9
   2:     0x7f0066389c2b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hbe741a5cc3c49508
   3:     0x7f00663898af - std::panicking::default_hook::he0146e6a74621cb4
   4:     0x7f006637a6ce - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
   5:     0x7f0066389e71 - std::panicking::begin_panic::he426e15a3766089a
   6:     0x7f006637b6aa - std::panicking::begin_panic_fmt::hdddb415186c241e7
   7:     0x7f0066389e0e - rust_begin_unwind
   8:     0x7f00663bfb1f - core::panicking::panic_fmt::hf4e16cb7f0d41a25
   9:     0x7f00663c6fda - core::str::slice_error_fail::ha8f4daeb58b867c4
  10:     0x7f0066161de1 - racer::scopes::mask_comments::ha8f29cea44f74bea
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/str/mod.rs:1399
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcollections/string.rs:1568
                        at /home/sekjun9878/.cargo/git/checkouts/racer-24fcc62dd34d070a/master/src/racer/core.rs:409
                        at /home/sekjun9878/.cargo/git/checkouts/racer-24fcc62dd34d070a/master/src/racer/scopes.rs:219
  11:     0x7f0066183e57 - racer::ast::find_type_match::h8946fce7fbd7e75f
                        at /home/sekjun9878/.cargo/git/checkouts/racer-24fcc62dd34d070a/master/src/racer/scopes.rs:28
                        at /home/sekjun9878/.cargo/git/checkouts/racer-24fcc62dd34d070a/master/src/racer/ast.rs:424
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/option.rs:572
                        at /home/sekjun9878/.cargo/git/checkouts/racer-24fcc62dd34d070a/master/src/racer/ast.rs:414
                        at /home/sekjun9878/.cargo/git/checkouts/racer-24fcc62dd34d070a/master/src/racer/ast.rs:385
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/option.rs:572
                        at /home/sekjun9878/.cargo/git/checkouts/racer-24fcc62dd34d070a/master/src/racer/ast.rs:382
  12:     0x7f006617c43c - racer::ast::path_to_match::h02e3671dad1620de
                        at /home/sekjun9878/.cargo/git/checkouts/racer-24fcc62dd34d070a/master/src/racer/ast.rs:372
  13:     0x7f0066180b48 - _<racer..ast..LetTypeVisitor<'c, 's> as syntex_syntax..visit..Visitor<'v>>::visit_local::h64fc0aa80fc52a1c
                        at /home/sekjun9878/.cargo/git/checkouts/racer-24fcc62dd34d070a/master/src/racer/ast.rs:312
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/option.rs:572
                        at /home/sekjun9878/.cargo/git/checkouts/racer-24fcc62dd34d070a/master/src/racer/ast.rs:310
  14:     0x7f006619f4d2 - racer::ast::get_let_type::hff92b12f1b6c42a3
                        at /home/sekjun9878/.cargo/registry/src/github.com-1ecc6299db9ec823/syntex_syntax-0.32.0/src/visit.rs:661
                        at /home/sekjun9878/.cargo/registry/src/github.com-1ecc6299db9ec823/syntex_syntax-0.32.0/src/visit.rs:67
                        at /home/sekjun9878/.cargo/registry/src/github.com-1ecc6299db9ec823/syntex_syntax-0.32.0/src/visit.rs:646
                        at /home/sekjun9878/.cargo/git/checkouts/racer-24fcc62dd34d070a/master/src/racer/ast.rs:979
  15:     0x7f0066186052 - racer::typeinf::get_type_of_match::h5ac64271f506c4db
                        at /home/sekjun9878/.cargo/git/checkouts/racer-24fcc62dd34d070a/master/src/racer/typeinf.rs:143
                        at /home/sekjun9878/.cargo/git/checkouts/racer-24fcc62dd34d070a/master/src/racer/typeinf.rs:252
  16:     0x7f006617ede1 - _<racer..ast..ExprTypeVisitor<'c, 's> as syntex_syntax..visit..Visitor<'v>>::visit_expr::hda0d92c35f88d9d7
                        at /home/sekjun9878/.cargo/git/checkouts/racer-24fcc62dd34d070a/master/src/racer/ast.rs:452
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/option.rs:572
                        at /home/sekjun9878/.cargo/git/checkouts/racer-24fcc62dd34d070a/master/src/racer/ast.rs:447
  17:     0x7f0066164fd2 - racer::ast::get_type_of::h32f41f6902b0780f
                        at /home/sekjun9878/.cargo/registry/src/github.com-1ecc6299db9ec823/syntex_syntax-0.32.0/src/visit.rs:648
                        at /home/sekjun9878/.cargo/git/checkouts/racer-24fcc62dd34d070a/master/src/racer/ast.rs:965
  18:     0x7f0066162156 - racer::core::complete_from_file::h4a0b25b647ac5724
                        at /home/sekjun9878/.cargo/git/checkouts/racer-24fcc62dd34d070a/master/src/racer/core.rs:591
  19:     0x7f00660c71ab - std::panicking::try::call::h0cfda1b8f055da74
                        at /home/sekjun9878/.cargo/git/checkouts/racer-24fcc62dd34d070a/master/src/bin/main.rs:160
                        at /home/sekjun9878/.cargo/git/checkouts/racer-24fcc62dd34d070a/master/src/bin/main.rs:109
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:251
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:272
  20:     0x7f0066393aeb - __rust_try
  21:     0x7f0066393a8e - __rust_maybe_catch_panic
  22:     0x7f00660c7c83 - _<F as alloc..boxed..FnBox<A>>::call_box::he07b3ce5e1129128
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/thread/local.rs:211
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:235
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:307
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/liballoc/boxed.rs:544
  23:     0x7f0066388454 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
  24:     0x7f0065a670a3 - start_thread
  25:     0x7f006558687c - clone
  26:                0x0 - <unknown>
ERROR:racer: Search thread paniced: Any
END
sekjun9878@workstation1:~/Projects/news-test$ racer -V
racer 1.2.10

sekjun9878@workstation1:~/Projects/news-test$ 
```

```
extern crate regex;

#[macro_use]
extern crate log;
extern crate env_logger;

extern crate serde_json;
extern crate postgres;
extern crate select;
extern crate chrono;

use std::fs::File;
use std::io::Write;
use std::io::Read;
use std::collections::HashMap;

fn main() {
    let news: ReutersNews = "reuters.html".parse::<ReutersNews>().unwrap();
    news.
```
```
sekjun9878@workstation1:~/Projects/news-test$ rustc --version
rustc 1.11.0-nightly (ad7fe6521 2016-06-23)
sekjun9878@workstation1:~/Projects/news-test$ cargo --version
cargo 0.12.0-nightly (50dad37 2016-06-21)
```

**Comment by birkenfeld** [comment]
Would be fixed by https://github.com/phildawes/racer/pull/607/commits/c89a8fc9973b0047bd6e19fe9493518b1c039e50

**Comment by jwilm** [comment]
@birkenfeld's fix has landed on master; closing. Thanks for the report!

**Comment by sekjun9878** [comment]
Thanks!
