### ISSUE TITLE
racer can not handle utf-8 in comments

### ISSUE THREAD

**Issue by Dushistov** [phildawes/racer#711]
```
thread 'main' panicked at 'byte index 4 is not a char boundary; it is inside 'т' (bytes 3..5) of `///т.к. `SystemTime` не реализует Encodable и Decodable`', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/str/mod.rs:1771
stack backtrace:
   1:     0x5618cf67ea6c - std::sys::imp::backtrace::tracing::imp::write::h23bcdb89e70c5bbf
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x5618cf68374e - std::panicking::default_hook::{{closure}}::he7b82439fd2d2bb6
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x5618cf683354 - std::panicking::default_hook::he1cd4269c1558f23
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libstd/panicking.rs:367
   4:     0x5618cf683beb - std::panicking::rust_panic_with_hook::h006b37e36b7c8982
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x5618cf683a34 - std::panicking::begin_panic::h043cddfdd3933cc4
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libstd/panicking.rs:517
   6:     0x5618cf6839a9 - std::panicking::begin_panic_fmt::h34e588bba6b8a2c2
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libstd/panicking.rs:501
   7:     0x5618cf683937 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libstd/panicking.rs:477
   8:     0x5618cf6b030d - core::panicking::panic_fmt::he52644573ecd78ff
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/panicking.rs:69
   9:     0x5618cf6b12d3 - core::str::slice_error_fail::h1a7d3e6a65ceaf40
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/str/mod.rs:1771
  10:     0x5618cf53ab1a - racer::matchers::find_doc::h68c797b123d86242
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/str/mod.rs:1531
                        at /home/evgeniy/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-2.0.6/src/racer/matchers.rs:715
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/ops.rs:2706
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/option.rs:383
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/iter/mod.rs:999
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcollections/vec.rs:1662
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcollections/vec.rs:1645
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcollections/vec.rs:1532
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/iter/iterator.rs:1218
                        at /home/evgeniy/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-2.0.6/src/racer/matchers.rs:706
  11:     0x5618cf5327f1 - racer::matchers::match_types::h2d0b18a299d79676
                        at /home/evgeniy/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-2.0.6/src/racer/matchers.rs:405
                        at /home/evgeniy/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-2.0.6/src/racer/matchers.rs:34
  12:     0x5618cf51f8dd - racer::nameres::run_matchers_on_blob::hbdd245567a0910db
                        at /home/evgeniy/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-2.0.6/src/racer/nameres.rs:947
  13:     0x5618cf51e99f - racer::nameres::search_scope::h417a2610804bc116
                        at /home/evgeniy/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-2.0.6/src/racer/nameres.rs:894
  14:     0x5618cf526107 - racer::nameres::search_local_scopes::hb411720f7e8afc29
                        at /home/evgeniy/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-2.0.6/src/racer/nameres.rs:984
  15:     0x5618cf527e6a - racer::nameres::resolve_name::h7be65a7a74fff89a
                        at /home/evgeniy/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-2.0.6/src/racer/nameres.rs:1124
  16:     0x5618cf52aeff - racer::nameres::resolve_path::hef59c7c2c5e97668
                        at /home/evgeniy/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-2.0.6/src/racer/nameres.rs:1203
  17:     0x5618cf4f3697 - racer::core::find_definition_::h0f606403e92bc753
                        at /home/evgeniy/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-2.0.6/src/racer/core.rs:1084
  18:     0x5618cf467135 - racer::run::h050b927d6ab502d6
                        at /home/evgeniy/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-2.0.6/src/racer/core.rs:1038
                        at /home/evgeniy/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-2.0.6/src/bin/main.rs:161
                        at /home/evgeniy/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-2.0.6/src/bin/main.rs:411
  19:     0x5618cf4666b4 - racer::main::hf469dda717173afa
                        at /home/evgeniy/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-2.0.6/src/bin/main.rs:397
  20:     0x5618cf68aafa - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  21:     0x5618cf684356 - std::rt::lang_start::h1ef940195e3c010e
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libstd/panicking.rs:436
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libstd/panic.rs:361
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libstd/rt.rs:57
  22:     0x7f6f6bc5deaf - __libc_start_main
  23:     0x5618cf4461e8 - _start
  24:                0x0 - <unknown>
```

**Comment by ArtemGr** [comment]
Getting a similar error with a code using
```
#![feature(non_ascii_idents)]
#![allow(unknown_lints, uncommon_codepoints)]
```

such as

```
  let (req, reqᵇ) = req.into_parts();
```

```
[2020-04-05T19:48:35Z ERROR rls::actions::hover] racer_def: racer panicked
thread 'request-worker-3' panicked at 'byte index 5798 is not a char boundary; it is inside 'ᵇ' (bytes 5796..5799) of `
```
